### ISSUE TITLE
0.0.5 - Task List (provisional)

### ISSUE THREAD

**Issue by oOKexOo** [oOKexOo/AresModAchillesExpansion#32]
### Changes:
- [x] Garrison module: Replace searching pattern "House" by "Building" (=> more buildings are available e.g. Tanoa WW2 bunkers).
- [x] Moved "Create/Edit intel" module from "spawn" to "scenario flow" category (see #40)
- [x] "Destroy Buildings" Module was changed to "Damage Buildings" Module (=more options).
- [x] "Patrol" module was changed to "Patrol/Loiter (Heli)" => Loiter waypoint for aircrafts.
- [x] Default assigned hotkey to eject passengers has changed from `LEFT SHIFT` + `G` to `V`.
- [x] For logged-in admins the "execute code" module is in any case available.
- [x] "Bind variable to object" variable is no longer public, but still global.
- [x] Postpone initialization of global functions to the point they are needed.

### Features:
- [x] Toggle street lamps module
- [x] Autocollapse Tree (see #26) 
- [x] Apex symbol in front of apex objects and warning message ~~(make aware of non-Apex owner kick issue).~~
- [x] CBA settings framework (by @Grezvany13).
- [x] Settings: Helmet & DLC icons for module tree (by @Grezvany13).
- [x] Settings: Zeus vison modes (by @Grezvany13).
- [x] Settings: Set available factions for module tree (especially useful for addons like CUP).
- [x] Settings: Customizable hotkeys.
- [x] Waypoint: Paradrop waypoint.
- [x] Waypoint: Improved fastroping waypoint; ACE3 or Advanced Rappeling (AR) is needed. The latter is used if both are loaded. (Note that ACE3 fastroping does not work properly in MP in contrast to AR)
- [x] Reinforcement Module: Type of waypoint can be selected: Land, fastroping or paradrop.
- [x] JIP option for execute code.
- [x] Module "Change Altitude": Change altitude for aircrafts, divers and submarines (Note: In some cases you have to place a waypoint to get the desired effect!).
- [x] Improve "Add objects to Zeus" module (shorter radius, Filters)

### Fixes:
- [x] Non-local surrendered units stuck after release in cetain cases.
- [x] Implement solution similar to CED (see #27).
- [x] Player manned vehicles cannot be edited (see [BIS forum](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3132117))
- [x] Advanced attributes do not work for non-local units (see #38)
- [x] "Garrison building instant" module does not work for non-local units.
- [x] Suppressive fire does not work properly with move waypoints.
- [x] ~~Suppressive fire could be spamed => led to unexpected behaviour.~~ (Rejected)
- [x] ~~Suppressive fire: Units do not aim at target from the very beginning.~~ (No solution found)
- [x] Mines were marked on map (check ACE3 solution?)
- [x] Mortar only fire one shell (see #36)

**Comment by oOKexOo** [comment]
### Features:

- [ ] Introduce group/ungroup option as a general concept.
- [ ] Autocollapse Tree (see #26) 
- [ ] Apex symbol in front of apex objects and warning message (make aware of non-Apex owner kick issue).
- [ ] Add missing empty objects from vanilla (available in Eden).
- [ ] JIP option for execute code.
- [ ] Entry about advanced compositions in field manual.
- [ ] Import/export function for advanced compositions.
- [ ] Change flying altitude.

**Comment by oOKexOo** [comment]
### Fixes:
- [ ] Suppressive fire does not work properly with move waypoints.
- [ ] Suppressive fire could be spamed => led to unexpected behaviour.
- [ ] Mines were marked on map (check ACE3 solution?)

**Comment by oOKexOo** [comment]
completed
