### ISSUE TITLE
0.0.6 - Task List (provisional)

### ISSUE THREAD

**Issue by oOKexOo** [oOKexOo/AresModAchillesExpansion#33]
### Changes:
- [x] Create Intel: Simulation of new created intel is no longer enabled.
- [x] Ammo box inventory is no longer opened automatically on spawn.
- [x] Add/Remove editable objects: Extend search pattern to static turrets for type "units" and "vehicles".
- [x] Update ACE module category name to ACE3 3.9.0.
- [x] "Bind variable to object" module: Global variable is optional.
- [x] Enlarge Attributes window to prevent the need of scroll bars.
- [x] Intel: enlarge description section.
- [x] Maximal # rounds for arty changed to 10.
- [x] Improve inventory dialog (improved performance by caching data; separated virtual arsenal (VA) from normal inventory; numpad keybinding: +/- (useful to make fast changes), * = VA, / = weapon sepecific); double click on weapon => weapon specific; sorted alphabetic, press letter/number to switch between entries; include faceware)
### Features:
- [x] Fire Support: Attack chopper CAS (target logic + module; might be laggy)
- [x] Names of target/LZ/RP logics can be specified.
- [x] Ares_fnc_showChooseDialog: New control type: "MESSAGE" (see [Achilles Wiki](https://github.com/oOKexOo/AresModAchillesExpansion/wiki/Custom-Modules))
- [x] Settings: Auto-collapse module tree is optional
- [x] Implement scroll bar for Ares_fnc_showChooseDialog
- [x] Pre-placing mode (Allows defining spawn position prior to spawning the asset/module; especially useful for carriers).
- [x] Additional way to spawn vehicles without crew.
- [x] Edit unit attributes: Change unit traits (Medic, EOD, engineer); Vanilla & ACE3 version.
- [x] Change Ability: PATH (by @Grezvany13).
- [x] ~~Define unit attributes for future spawned units (saves a lot of time)~~ (replaced by the feature below).
- [x] Attributes window: Changed attributes are applied on all selected units/vehicles/ammo boxes/groups (as in Eden editor; real game changer!).
- [x] ~~Implement [BIS_fnc_unpackStaticWeapon](https://community.bistudio.com/wiki/BIS_fnc_unpackStaticWeapon) and [BIS_fnc_packStaticWeapon](https://community.bistudio.com/wiki/BIS_fnc_packStaticWeapon)~~ (Does not work properly atm).
### Fix:
- [x] Healing module did not work for non-local units.
- [x] Patrol/Loiter Module: Fails when chopper is not in the air.
- [x] Ares_fnc_ShowChooseDialog: Variable scope issue ([BIS forum](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3157509))
- [x] If fog decay was set to 0 a strange behaviour was observed (see [youtube](https://www.youtube.com/watch?v=vksk_BiC3o4)).
- [x] Achilles object attributes are incomptatible with "Set Attributes - X" modules.
- [x] Damage vehicle components: Not all components were available and some component names went missing.
- [x] Translation corrections for German (by @KiritoKun223)
- [x] Factions with apostrophe in the name lead to errors (fixed by @shukari).
- [x] Unessecary creation of dependency on achilles_data_f_achilles when placing compositions in Eden ([BIS Forum](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3140115)).
- [x] Mines were still revealed to players (0.0.5 only removed the map markers...).
### Review:
- [x] ~~Missing attributes in certain cases (see [BIS Forum](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3146159))~~ (resolved).
