### ISSUE TITLE
0.0.7 - Task List (provisional) 

### ISSUE THREAD

**Issue by oOKexOo** [oOKexOo/AresModAchillesExpansion#50]
### Changes:
- [x] ACE injury module: Adjusted damage levels.
- [x] Removed side restriction for vanilla CAS modules.
- [x] Radial searches are now conducted in 2D (ignoring z) instead of 3D (e.g. damage buidlings).
- [x] All dialog windows are movable now.
- [x] Module "Hint" makes use of "MESSAGE" control type.
- [x] Forced advanced hint window for selection option.
- [x] Cargo Attributes: Larger dialog window.
- [x] Replace icon for CAS Target.
- [x] ~~Artillery Fire Module: Remove mortar workaround (BIS fixed it by now)~~ (done in hotfix 0.0.6d).
- [x] ~~Skip time module: Set exact time~~ (cancled: set date module is the method of choice)
- [x] Replace waitUnit delete by "deleted" event handler (e.g. advanced compositions).
### Features:
- [x] Make object invincible module.
- [x] Suppressive fire module: Line-up is now an option and no longer handled automatically.
- [x] ACE injury module: injury types, pain level, blood volume and hearth rate.
- [x] Add/remove Zeus objects can now handle simple objects (EXPERIMENTAL - DO NOT YET SUPPORT FEATURES SUCH AS COPY/PASTE, ADV. COMPOSITIONS, SAVE MISSION SQF, ...).
- [x] Show config and animation viewer modules.
- [x] Vehicle garage from Eden editor.
- [x] Create TPs: Custom names can be given to teleport flags.
- [x] Hint Module: Support XML syntax (allows including images).
- [x] Recovered vanilla CAS bomb strike module (dunno why it was hidden).
- [x] Vanilla CAS modules: Implemented general config solution => support any 3rd party add-on.
- [x] Implement additional ambient animations (see comment by [GHC] RandomMusic).
- [x] Set date module.
- [x] ~~Add missing empty objects from vanilla (available in Eden)~~ (Would lead to unintended add-on dependencies).
- [x] Attribute window for light sources: RGB, radius and attenuation.
- [x] "Lock door" module (including breach option) and incorporate [animateSource](https://community.bistudio.com/wiki/animateSource) script command (also useful for [offroad police light](https://forums.bistudio.com/topic/147049-setting-color-of-offroad/), etc.).

### Fixes:
- [x] Went missing in previous versions: Instant occupation does distribute large group (>8 members) on different buildings (@Grezvany13)
- [x] ACE injury module: Untreatable unconsciousness.
- [x] Suppressive fire module: Did not work for non-local units.
- [x] Add/remove Zeus objects: Exclude curator module from being added to Zeus interface.
- [x] Locality issue with vectordir and -up changes (e.g. Spawn Advanced Compositions).
- [x] Pressing attribute buttons (e.g. arsenal) undid changes of attributes in the main window.
- [x] Effect modules were placed by setVehiclePosition algorithm (inaccurate position).
- [x] Punishment module was missing.
- [x] Force AI to chute: Exception handling for units that already have a chute was missing.
- [x] Syntax error in dynamic dialog cfg   (fixed by @shukari)
- [x] Missing error message for modules such as "Hava a seat".

### Review:
- [x] Proxy function for remote execution (see [Steam Discussion](http://steamcommunity.com/workshop/filedetails/discussion/723217262/135511027315798288/))
- [x] setRank/setUnitRank should be global in 1.64.
- [x] BIS_fnc_unpackStaticWeapon / BIS_fnc_packStaticWeapon should be fixed in 1.64.
- [x] ~~"Have a chair" module (locality issue with animation?)~~ (no issue observed)
- [x] Review ACE3 injury module ([BIS Forum](https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?do=findComment&comment=3139556))
