### ISSUE TITLE
0.0.8 - Task List (provisional)

### ISSUE THREAD

**Issue by oOKexOo** [oOKexOo/AresModAchillesExpansion#91]
### Changes:
- [x] Carrier base gets added automatically; Deletion will affect all carrier parts (the carrier is not movable though).
- [x] Intel: The map only opens for the player that picked it up. Who actually gets the intel as well still depends on the settings.
- [x] Heal and injury modules check for ace_medical instead of ace_main (by @CreepPork).

### Features:
- [x] Promote player to Zeus; This module is only available for admins when the execute code module is disabled; The rights are lost when the player respawns or disconnects (by @CreepPork).
- [x] Function Viewer Module (Dev Tools).
- [x] Switch Unit, an alternative to remote control, which gives full control over the unit (hotkey: LSHIFT + 2xLMB).
- [x] Side as a group attribute (new attribute button).
- [x] Change Zeus vision mode brightness (feature inspired by ACE3; ALT+PAGE UP/DOWN by default)
- [x] IED and Suicide Bomber modules (by @CreepPork).
- [x] Implemented Achilles_fnc_addCuratorInterfaceEventHandler.
- [x] Added "allow fleeing" parameter to AI ability module.

### Fixes:
- [x] USS Freedom: Spawned twice in certain cases.
- [x] Vanilla cycle waypoint issue for copied units (waypoint ended up on map origin).
- [x] Ammo slider (vehicle attributes): Did not handle dynamic loadouts correctly.
- [x] Align object horizontal (default key: X): Did not execute Achilles_fnc_HandleCuratorObjectEdited.
- [x] Dynamic Dialog Side Control: Clicking on current selected side led to unintended behaviour.
- [x] Canceling selection option: Did not work properly for a few modules.
- [x] "Selection option" and "specify position" modes missed exception handling: Exiting Zeus interface.
- [x] "Specify position" in recent tab was also executed for Zeus modules and multiple times for groups.
- [x] "Create/Edit Intel" did not handle newline characters (Hotkey: LSHIFT+RETURN).
- [x] Create/Edit Intel: Dialog title did not describe the exact action (create, spawn or edit). 

### Remarks:
- [x] txt files have changed => Adjust links on Steam and BIS forum accordingly!
